jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - continue-on-error: true
      id: previoustag
      name: Get Previous tag
      uses: WyriHaximus/github-action-get-previous-tag@v1
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: replace version
      run: ver=${{ steps.previoustag.outputs.tag }} && new_ver=${ver:1} && sed -i
        "s/SONIC_VERSION/${new_ver}/g" pom.xml
    - continue-on-error: true
      name: login docker hub
      run: echo "${{ secrets.ACCESS_TOKEN }}" | docker login -u zhouyixun --password-stdin
    - continue-on-error: true
      name: Validate and Compile with Maven
      run: mvn package -Dmaven.test.skip=true
    - continue-on-error: true
      name: deploy controller
      run: docker build -t sonicorg/sonic-server-controller:${{ steps.previoustag.outputs.tag
        }} -f sonic-server-controller/src/main/docker/Dockerfile .
    - continue-on-error: true
      name: push controller
      run: docker push sonicorg/sonic-server-controller:${{ steps.previoustag.outputs.tag
        }}
    - continue-on-error: true
      name: deploy eureka
      run: docker build -t sonicorg/sonic-server-eureka:${{ steps.previoustag.outputs.tag
        }} -f sonic-server-eureka/src/main/docker/Dockerfile .
    - continue-on-error: true
      name: push eureka
      run: docker push sonicorg/sonic-server-eureka:${{ steps.previoustag.outputs.tag
        }}
    - continue-on-error: true
      name: deploy gateway
      run: docker build -t sonicorg/sonic-server-gateway:${{ steps.previoustag.outputs.tag
        }} -f sonic-server-gateway/src/main/docker/Dockerfile .
    - continue-on-error: true
      name: push gateway
      run: docker push sonicorg/sonic-server-gateway:${{ steps.previoustag.outputs.tag
        }}
    - continue-on-error: true
      name: deploy folder
      run: docker build -t sonicorg/sonic-server-folder:${{ steps.previoustag.outputs.tag
        }} -f sonic-server-folder/src/main/docker/Dockerfile .
    - continue-on-error: true
      name: push folder
      run: docker push sonicorg/sonic-server-folder:${{ steps.previoustag.outputs.tag
        }}
name: deploy to dockerHub
on:
  repository_dispatch:
    types: trigger-ga___deploy.yml
