jobs:
  build:
    needs: create
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - continue-on-error: true
      id: previoustag
      name: Get Previous tag
      uses: WyriHaximus/github-action-get-previous-tag@v1
    - continue-on-error: true
      name: replace version
      run: sed -i "s/SONIC_VERSION/${{ steps.previoustag.outputs.tag }}/g" docker-compose*.yml
    - continue-on-error: true
      name: mkdir
      run: mkdir -p sonic-server-${{ steps.previoustag.outputs.tag }}/imageFiles sonic-server-${{
        steps.previoustag.outputs.tag }}/keepFiles sonic-server-${{ steps.previoustag.outputs.tag
        }}/logs sonic-server-${{ steps.previoustag.outputs.tag }}/packageFiles sonic-server-${{
        steps.previoustag.outputs.tag }}/recordFiles
    - continue-on-error: true
      name: copy
      run: cp .env docker-compose*.yml sonic-server-${{ steps.previoustag.outputs.tag
        }}/
    - continue-on-error: true
      name: zip
      uses: TheDoctor0/zip-release@0.6.2
      with:
        directory: sonic-server-${{ steps.previoustag.outputs.tag }}
        filename: sonic-server-${{ steps.previoustag.outputs.tag }}.zip
    - continue-on-error: true
      name: move outside
      run: mv sonic-server-${{ steps.previoustag.outputs.tag }}/sonic-server-${{ steps.previoustag.outputs.tag
        }}.zip ./sonic-server-${{ steps.previoustag.outputs.tag }}.zip
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Upload To Github Release
      uses: xresloader/upload-to-github-release@v1.3.4
      with:
        draft: false
        file: sonic-server-${{ steps.previoustag.outputs.tag }}.zip
        tag_name: ${{ steps.previoustag.outputs.tag }}
        update_latest_release: true
  create:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        generate_release_notes: true
name: release to github
on:
  repository_dispatch:
    types: trigger-ga___release.yml
